version: "3.9"
services: 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  library:
    build: ./
    container_name: library-nest
    ports:
      - 80:${PORT}
    environment:      
      - PORT=${PORT}
    command: sh -c "cd /app; rm -rf node_modules; npm install; npm run start"
