version: "3.9"
services: 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  hotel-aggregator:
    build: ./
    container_name: hotel-aggregator
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    environment:      
      - PORT=${PORT}
    command: sh -c "cd /app; rm -rf node_modules; npm i -g @nestjs/cli; npm install; npm run build; npm run start:prod"
