version: "3.9"
services: 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - hotels_network


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
    networks:
      - hotels_network

  postgres_postgis:
    image: postgis/postgis
    container_name: postgres_postgis
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATA: ${POSTGRES_DATA}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - hotels_network

  adminer_pgadmin4:
    image: dpage/pgadmin4
    container_name: adminer_pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8090:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - hotels_network

  hotel-aggregator-dev:
    build: ./ 
    container_name: hotel-aggregator-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${DEV_PORT}:${DEV_PORT}
    depends_on:
      - mongo
      - postgres_postgis
    env_file:
      - .env
    environment:
      - PORT=${DEV_PORT}
      - SECRET=${SECRET}
      - IS_DEV=true
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm i -g @nestjs/cli; npm install; npm run start:dev"
    networks:
      - hotels_network

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:

networks:
  hotels_network:
    driver: bridge