version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  postgres_postgis:
    image: postgis/postgis
    container_name: postgres_postgis
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATA: ${POSTGRES_DATA}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  hotel-aggregator:
    build: ./backend
    container_name: hotel-aggregator
    volumes:
      - ./backend:/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
      - postgres_postgis
    environment:
      - PORT=${PORT}
      - SECRET=${SECRET}
    command: sh -c "cd /app && npm install && npm run build && npm run start:prod"

volumes:
  mongo_data:
  postgres_data:

